# ruff.toml

exclude = [
    "skyflow/generated",
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "build",
    "dist",
    "tests",
    "samples"
]

line-length = 120

[lint]
select = ["N", "PLR2004"]

[lint.pep8-naming]
